name = "community-call-bot"
main = "src/index.ts"
compatibility_date = "2022-12-26"
account_id = "db47db45acd22a503f31e76887a98caa"

[vars]
DISCORD_APPLICATION_ID = "1056871531894034492"
DISCORD_PUBLIC_KEY = "dabf0b0d062af6d1a4ab28fa5499984e3ef5e09b662f8e1fdb75cf232aa1136c"

[[kv_namespaces]]
binding = "Settings"
id = "fb89bffc17f84ea9830235274da40fd5"
preview_id = "fb89bffc17f84ea9830235274da40fd5"

# [secrets]
# DISCORD_BOT_TOKEN - this is used for setting commands, as well as posting announcements for questions
# DISCORD_QUESTIONS_WEBHOOK - this is used for posting questions. It must be a complete webhook URL, 
#	including the secret, for example https://discord.com/api/webhooks/1234567890/abcdefg