name: Checks
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js 16.17
        uses: actions/setup-node@v3
        with:
          node-version: 16.17
          cache: "npm" # cache ~/.npm in case 'npm ci' needs to run

      - name: Install NPM Dependencies
        run: npm ci

      - name: Check for formatting issues
        run: npm run format

      - name: Check for linting issues
        run: npm run lint

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js 16.17
        uses: actions/setup-node@v3
        with:
          node-version: 16.17
          cache: "npm" # cache ~/.npm in case 'npm ci' needs to run

      - name: Install NPM Dependencies
        run: npm ci

      - name: Run build
        run: npm run build
